### ISSUE TITLE
Using vue-router with StateHelper pushes state names as route paths instead of as route names

### ISSUE THREAD

**Issue by twoBoots** [davestewart/javascript-state-machine#14]
Steps to reproduce:

Modify the route paths in the example `demo/html/examples/vue/vue-router.html` vue-router configuration lines 59-69:
```
var router = new VueRouter({
    mode: 'hash',

    // note that route names match state names
    routes: [
        { path: '/state-a', name: 'a', component: StateA },
        { path: '/state-b', name: 'b', component: StateB },
        { path: '/state-c', name: 'c', component: StateC },
        { path: '*',  name: '*', component: NotFound }
    ]
});
```

Run:
```
npm run demo
```

**Comment by davestewart** [comment]
Hmm, interesting. I wrote that a while ago now so not sure why I had the comment "note that route names match state names".

I agree with you though, that route names should definitely be independent of state names though, otherwise it's limiting.

I'll look into that to try and determine what my intentions were and will update if required.

**Comment by twoBoots** [comment]
I think that route names have to be used, as the state machine throws a transition shorthand error in the following example:

Route config:
```
routes: [
    { path: '/x/first',  name: 'first', component: StateA },
    { path: '/x/second', name: 'second', component: StateB },
    { path: '/complete', name: 'complete', component: StateC },
    { path: '*',  name: '*', component: NotFound }
]

**Comment by davestewart** [comment]
We'd have to use state names in the transitions, but I imagine that we could use the original routes array as a lookup to get the state names.

I'm surprised I didn't solve this before, but I will get it done.

**Comment by twoBoots** [comment]
Yep, agree. 

I got this done in PR #15

**Comment by davestewart** [comment]
Ah, not quite.

I meant we could use paths in the router, but states in the FSM.

Bedtime for me now, but I'll hopefully get to take a look at this at the weekend

**Comment by davestewart** [comment]
@twoBoots Checked it out and your fix was spot on. Thanks!
