### ISSUE TITLE
readable example?

### ISSUE THREAD

**Issue by crostine** [davestewart/javascript-state-machine#16]
Hi,

the demo is not readable as it is webpack compiled... 
do you have an example that does not require all the browser bullshit to be in the way?

**Comment by davestewart** [comment]
Short answer: no.

Longer answer: you can copy most of the demo code to NPM's Run Kit and try there:

- https://npm.runkit.com/state-machine

```
var StateMachine = require("state-machine").StateMachine

var config = {

  transitions: [
    'next    : a > b > c > d',
    'back    : a < b < c < d',
    'restart : a < b   c   d',
    'exit    : a   b   c   d > x'
  ],

  handlers: {
    'change': function (event, fsm) {
      console.log('Config handler: state is now ' + event.value);
    }
  }

};

var fsm = new StateMachine(config);

fsm.do('next')
fsm.do('next')
fsm.do('next')
fsm.do('exit')
```

I could also add a section to the demo regarding Node, which is not something I had considered thus far :)

**Comment by crostine** [comment]
so if i understand correctly from this example, you cant define the actual states?
is it just magic between handlers and transitions?

if i were to make a handler will it be triggered with every change like the 'change' example, or doesnt it trigger that way at all?

**Comment by davestewart** [comment]
Did you look at the demo pages?

- http://statemachine.davestewart.io/html/api/index.html

They go through each type of setup, both shorthand (what you see above) and object configuration.

Not sure what you mean by "magic".

You have incredible amounts of control on when handlers fire.

More information available in:

- The [demo](http://statemachine.davestewart.io/html/api/events/playground.html)
- The [documentation](https://github.com/davestewart/javascript-state-machine/blob/master/docs/api/events.md)

Probably best to read the docs and try the demo first. I spent a LOT of time trying to get them just right. If there's something that's unclear (after having read them) I would be happy to help to clarify any issues and if necessary, make the docs better.
