### ISSUE TITLE
multiple state machines on the same page using Vue

### ISSUE THREAD

**Issue by shaal** [davestewart/javascript-state-machine#21]
I was trying to use [vue-reactive.html](https://github.com/davestewart/javascript-state-machine/blob/master/demo/html/examples/vue/vue-reactive.html
) demo, to create 2 separate state machines on the same page.
but the only way I was able to do it, was to duplicate so many things.

I saw that in the project that inspired this one, they have a State Machine Factory
https://github.com/jakesgordon/javascript-state-machine/blob/master/docs/state-machine-factory.md

What's the best way to create another state machine?

**Comment by davestewart** [comment]
Hey shaal, sorry to hear you're having difficulties. What did you need to duplicate? It should hear work! Can you share a is fiddle or such like?

**Comment by shaal** [comment]
I created the (working) example here - https://jsfiddle.net/shaal/vgxvhs0b/10/

What I was trying to figure out, is like there's a line 
`this.state = StateHelper.object(this.fsm).data;`

creating something like 
`this.newState = StateHelper.object(this.fsm).data;`
and because `fsm` already details the finite-machine-state needed, it can just be duplicated and used for another set of elements, as newState. (like the example I posted here but in a much cleaner way with less duplicated code)

Thank you!

**Comment by davestewart** [comment]
Looks like from the fiddle that you got it working then!
