### ISSUE TITLE
Programmatic transition not firing state:a:enter handler 

### ISSUE THREAD

**Issue by fieldfoxWim** [davestewart/javascript-state-machine#23]
Hi Mr Stewart

After some research I decided to use your implementation of an FSM for a project of mine. Where I stumbled upon the following issue:

When a programmatic transition is used, as in this [example](https://statemachine.davestewart.io/html/api/handlers/programmatic.html) , the `state:a:enter` event is not fired.

An example of this is shown in the following gist.run: 
https://gist.run/?id=6c69f5a4fa2787a95cfbb65dfd4a4c50

My suspicion is that during the creation of the transition, for the `state:a:enter` the to param is a function, while handlers array creation uses regex replacement as if it were a string.

Please advise, I might be able to fix the issue with some guidance.

Best regards
Wim

**Comment by davestewart** [comment]
Hey, that's a bit weird isn't it. Let me look at that as soon as I get some time. I haven't looked at this project for a few years!
